# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 
# Fibonacci Generator Function
f0, f1 = 1, 2
fn = -1
sum = f1
fibo = [1, 2]
n = len(fibo)

while True:
    fibo.append(fibo[n-1] + fibo[n-2])
    if fibo[n] > 4e6:
        break
    n += 1

# list comprehensive
even_fibo = [k for k in fibo if k % 2 == 0]
print(even_fibo)

even_fibo = []
for k in fibo:
    if k % 2 == 0:
        even_fibo.append(k)

