# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 
# Fibonacci Generator Function
f0, f1 = 1, 2
fn = -1
sum = f1
while fn < 4e6:
    fn = f0 + f1
    f0, f1 = f1, fn

    # Fliter only even numbers
    if fn % 2 == 0:
        # Sum all value from filtered
        sum += fn
print(sum)

# Refactoring

